### ISSUE TITLE
template and mapping files aren't respected

### ISSUE THREAD

**Issue by xentac** [madhat2r/plaid2text#10]
I tried setting the values (mapping_file and template_file) in both the DEFAULT and account-specific sections and they never seem to be read.

accounts_file and journal_file are being read and respected, so it's a little strange.

**Comment by madhat2r** [comment]
I beleive I have found the bug. User paths were not being expanded, so harcoded paths worked, but paths starting with `~` did not. 

Please confirm that this was your issue. Thanks.

**Comment by xentac** [comment]
This fixed my problem.
