### ISSUE TITLE
Error: max number of additions on first account

### ISSUE THREAD

**Issue by philipsd6** [madhat2r/plaid2text#15]
I followed the instructions to set up my Plaid account, and got my developer client_id and secret. (My `~/.config/plaid2text/config` file contains them after my first run.) Then I followed the steps to add my first account (details anonymized)
```
$ plaid2text my_checking --create-account
/home/philipsd6/.local/venvs/beancount/lib/python3.5/site-packages/plaid/client.py:155: UserWarning:
                Tartan is not intended for production usage.
                Swap out url for https://api.plaid.com
                via Client.config before switching to production
  ''')

What bank is this account going to be for?
[...]

Enter Number [q to quit]: <num_of_my_bank>

Enter the required credentials for My Bank

Username (User ID): myusername
Password (Password): ************
You have reached the maximum number of additions. Contact us to raise your limit.
New account my_checking successfully created.
```

I tried with several different banks with the same results, even with bogus account details. Do I need to upgrade to the Plaid production environment to do this? I didn't think that was necessary for getting started.

**Comment by philipsd6** [comment]
Not sure why this needed to be done right off the bat, but Plaid raised my limits on my request.

**Comment by madhat2r** [comment]
Not sure what was going on there. I never had any issue. 

I am glad you have it resolved.
