### ISSUE TITLE
Ability to specify mongodb host and port

### ISSUE THREAD

**Issue by xentac** [madhat2r/plaid2text#5]
I want to run plaid2text within a couple of docker containers and to do that I need to be able to specify host and port for the mongo server.

It might be nice to have that in the config file...

**Comment by madhat2r** [comment]
I will look into this when I get a bit more time...

**Comment by madhat2r** [comment]
Implemented this. Check out the docs for `mongo_db_uri` it accepts a mongodb uri formatted string, let me know if this gets it for you.

**Comment by xentac** [comment]
Yes, this worked for me.
