### ISSUE TITLE
Trailing spaces make me sad

### ISSUE THREAD

**Issue by xentac** [madhat2r/plaid2text#8]
{posting_account:<60} really shouldn't have the ":<60" in it because there's nothing at the end of the line.

Similarly, the transaction line would be way better without the trailing tags space if there are no tags:

{transaction_date} {cleared_character} "{payee}" "" {tags}

I'm sure the template supports that, but I'm not sure how.

**Comment by madhat2r** [comment]
Updated default template to remove ":<60". Also changed the way tags are handled. Now they are prefixed with a space if existent, allowing for no trailing spaces. See updated documentation for details.
